### ISSUE TITLE
Mobile apps ?

### ISSUE THREAD

**Issue by shtefcs** [mattfeldman/nullchat#162] opened 2015-05-23 04:40 UTC
I am just wondering is it possible to put null chat into native mobile apps for IOS & Android using Cordova ?

Btw, you created awesome thing dude, tnx for sharing it !

**Comment by mattfeldman** [comment] 2015-06-27 03:11
The current implementation with Semantic UI would likely not be sufficient.  I would likely use https://github.com/meteoric/meteor-ionic

**Comment by mattfeldman** [comment] 2015-06-27 16:09
Duplicate of  #58

**Closed by mattfeldman** 2015-06-27 16:09 UTC
